spring.application.name=demo
# Habilita o console web do H2
spring.h2.console.enabled=true
DB_CLOSE_DELAY=-1
spring.h2.console.path=/h2-console

# Configurações de conexão
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Configurações do JPA/Hibernate (opcional)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#utilitarios
spring.jackson.date-format=yyyy-MM-dd

